name: Run Tests

on: [pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.3', '7.4', '8.0']
                laravel: [8.82.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                  - laravel: 8.82.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                coverage: none

            - name: Install dependencies
              run: |
                composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
                
            - name: Notify slack test starting
              if: success()
              id: slack
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                channel: bot-channel
                status: STARTING
                color: warning

            - name: Execute tests
              id: tests
              run: vendor/bin/phpunit

            - name: Notify slack success
              if: steps.tests.outcome == 'success'
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                message_id: ${{ steps.slack.outputs.message_id }}
                channel: bot-channel
                status: SUCCESS
                color: good

            - name: Notify slack fail
              if: steps.tests.outcome == 'failure'
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                message_id: ${{ steps.slack.outputs.message_id }}
                channel: bot-channel
                status: FAILED
                color: danger
