name: tests

on: [pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['8.2']
                laravel: ['11.0']
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                  - laravel: '11.0'

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                coverage: none

            - name: Install dependencies
              run: |
                composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Execute tests
              id: tests
              run: vendor/bin/phpunit
